 # Programación para el Análisis de Datos
 ### Tarea 2
 ##### Presentado por: Kevin Alejandro Cardenas Quintero
 ##### Grupo 39
 ##### Código: 203008069
 ##### Presentado a: Felipe Alexander Pipicano Guzman
 ##### Universidad Nacional Abierta y a Distancia - UNAD
 ##### 2 de Abril 2024

# Ejercicio 2

Para este ejercicio, cargue de nuevo los datos del Ejercicio 1, pero genere un DataFrame llamado df, solamente con las columnas:

- type
- mass_kg
- year_built
- home_port
- name

Siguiendo las funciones mostradas en las referencias bibliográficas, desarrolle las siguientes tareas en el DataFrame generado anteriormente:

**Revisando datos faltantes:**

- Determine cuantos datos faltantes hay en la variable mass_kg del mediante value_counts()
- Crea un DataFrame df1 removiendo las filas que tienen algunos datos faltantes. Por otro lado crea un DataFrame df2 removiendo las filas que tienen todos los datos faltantes. Compáralos y comenta los resultados.
- En el DataFrame df completa los datos faltantes por los siguientes tres métodos (muestra y comenta los resultados):

  * Completar datos faltantes con el número 0.
  *  Completar por método de propagación hacia adelante.
  * Completar los valores faltantes con el promedio de la
columna.

**Operaciones de strings:**

Realice las siguientes operaciones en el DataFrame df:
-  De la columna home_port extraiga la primera palabra de cada
dato y muestre los resultados.
-  Determine cuántos datos comienzan con la palabra Port y cuántos
datos comienzan con una palabra diferente, ¿Cuáles son las
palabras diferentes?
- Filtre el DataFrame con los datos que en la columna name
contengan en el string la palabra “GO” y muestre los resultados.
- Convierta todos los strings de la columna name en palabras con
todas sus letras mayúsculas y muestre los resultados.
- Convierta todos los strings de la columna type en palabras con
todas sus letras minúsculas y muestre los resultados.
- Divida todos los strings de la columna home_port por el espacio
en blanco y muestre los resultados.
- Reemplace todas las palabras ‘Port’ que se encuentran en la
columna home_port por la abreviación ‘P.’ y muestre los
resultados.
- Comente todos los procesos realizados y concluya con las
posibilidades de uso de estas herramientas en su campo de acción.

## Teoria

**Limpieza y preprocesamiento de datos:**

La limpieza y el preprocesamiento de datos son etapas fundamentales en cualquier proyecto de análisis de datos. Consisten en identificar y corregir problemas en los datos, como valores faltantes, incorrectos o inconsistentes. Este proceso es crucial para garantizar la calidad de los datos y obtener resultados precisos y confiables en el análisis posterior.

**Segmentación y filtrado de datos:**

La segmentación y el filtrado de datos implican seleccionar subconjuntos específicos de datos basados en ciertos criterios o condiciones. Esto permite a los analistas centrarse en la información relevante para sus objetivos de análisis y explorar conjuntos de datos grandes y complejos de manera más efectiva.

**Normalización de datos:**

La normalización de datos se refiere al proceso de convertir los datos en un formato estándar y uniforme. Esto puede implicar convertir cadenas de texto en mayúsculas o minúsculas, estandarizar formatos de fechas o números, y eliminar caracteres especiales o espacios en blanco innecesarios. La normalización facilita la comparación y el análisis de los datos, así como evita errores debidos a diferencias en el formato.

## Paso 1. Preguntas:

Para este ejercicio, cargue de nuevo los datos del Ejercicio 1, pero genere un DataFrame llamado df, solamente con las columnas:
- type
- mass_kg
- year_built • home_port • name

In [ ]:
import requests
import pandas as pd

def obtener_datos():
    url = "https://api.spacexdata.com/v4/ships" #Formato String

    try:
        response = requests.get(url) #Trae los datos de la url
        response.raise_for_status()  # Si hay un error en la solicitud, lanzará una excepción
        datos_naves = response.json()  # Convertir la respuesta a formato JSON
        return datos_naves
    except requests.exceptions.RequestException as e:
        print("Error al realizar la solicitud:", e)
        return None

datos_naves = obtener_datos()

df = pd.DataFrame.from_dict(datos_naves)

df = df[["type", "mass_kg", "year_built", "home_port", "name"]] # Se seleccionan las columnas deseadas en el dataframe df

## Paso 2:

**Revisando datos faltantes:**

- Determine cuantos datos faltantes hay en la variable mass_kg del mediante value_counts()
- Crea un DataFrame df1 removiendo las filas que tienen algunos datos faltantes. Por otro lado crea un DataFrame df2 removiendo las filas que tienen todos los datos faltantes. Compáralos y comenta los resultados.

In [ ]:
df.mass_kg.value_counts(dropna=False) #Value_counts muestra la cantidad de naves que tienen el mismo peso. Al colocar dropna=False nos agrega los nullos

NaN          8
2719740.0    2
449964.0     2
89811.0      1
4616663.0    1
445428.0     1
2097411.0    1
741170.0     1
843682.0     1
312072.0     1
351080.0     1
266712.0     1
320236.0     1
508023.0     1
450870.0     1
502999.0     1
451778.0     1
273063.0     1
202302.0     1
440892.0     1
Name: mass_kg, dtype: int64

Se encuentran 8 valores nulos utilizando la funcion value_counts. Lo que permite esta funcion es contar las veces que tiene el mismo valos mass_kg

In [ ]:
df1 =  df.dropna() #remueve las filas con al menos un dato faltante
df2 = df.dropna(how="all") #remueve las filas que tengan todos los datos faltantes

print(len(df1))
len(df2)

21

29

Al eliminar las columnas con algun dato faltante queda un regisro de 21 naves. Al eliminar las filas que en su totalidad esten nulas se mantienen las 29 naves

## Paso 3

En el DataFrame df completa los datos faltantes por los siguientes tres métodos (muestra y comenta los resultados):

  * Completar datos faltantes con el número 0.
  *  Completar por método de propagación hacia adelante.
  * Completar los valores faltantes con el promedio de la
columna.

In [ ]:
# Completar datos faltantes con el número 0
df_zero = df.fillna(0) #filna indica con el valor que tu necesites reemplzar, en este caso 0

# Completar por método de propagación hacia adelante
df_propagacion = df.ffill() #Toma el valor anterior no nulo y con este valor completa el dato

# Completar los valores faltantes con el promedio de la columna
df_promedio = df.copy()
df_promedio.mass_kg = df.mass_kg.fillna(df.mass_kg.mean()) #filna indica con el valor que tu necesites reemplzar, en este caso el promedio de masa kg
df_promedio.year_built = df.year_built.fillna(df.year_built.mean()).astype(int) #filna indica con el valor que tu necesites reemplzar, en este caso el promedio del año y colocandolo entero
df_promedio

,type,mass_kg,year_built,home_port,name
0,Tug,2.667120e+05,1976,Port of Los Angeles,American Champion
1,Cargo,9.168381e+05,1998,Port of Los Angeles,American Islander
2,Cargo,9.168381e+05,1998,Port of Los Angeles,American Spirit
3,Barge,9.168381e+05,2021,Port Canaveral,A Shortfall of Gravitas
4,Tug,2.023020e+05,1974,Port of Los Angeles,Betty R Gambarella
5,Tug,2.730630e+05,1999,Port Canaveral,Elsbeth III
6,High Speed Craft,4.499640e+05,2014,Port Canaveral,GO Ms Chief
7,High Speed Craft,4.499640e+05,2015,Port Canaveral,GO Ms Tree
8,Cargo,4.517780e+05,2009,Port Canaveral,Shannon
9,Cargo,5.029990e+05,2007,Port Canaveral,GO Pursuit
10,Cargo,9.168381e+05,2014,Port Canaveral,GO Quest
11,Cargo,4.508700e+05,2010,Port Canaveral,Megan
12,Tug,5.080230e+05,1995,Port Canaveral,HAWK
13,Tug,3.202360e+05,1985,Fort Lauderdale,Hollywood
14,Barge,9.168381e+05,2014,Port Canaveral,Just Read The Instructions 1
15,Barge,9.168381e+05,2015,Port Canaveral,Just Read The Instructions 2
16,Tug,9.168381e+05,1998,Port of Los Angeles,Kelly C
17,Cargo,4.408920e+05,2002,Port of Los Angeles,NRC Quest
18,Barge,9.168381e+05,2015,Port of Los Angeles,Of Course I Still Love You
19,Tug,8.981100e+04,1976,Port of Los Angeles,Pacific Freeedom
20,Tug,3.510800e+05,1974,Port of Los Angeles,Pacific Warrior
21,Tug,3.120720e+05,1976,Port Canaveral,RACHEL
22,Tug,8.436820e+05,1975,Port Canaveral,Finn Falgout
23,Tug,7.411700e+05,2003,Port Canaveral,Lauren Foss
24,Cargo,2.097411e+06,2014,Port Canaveral,Shelia Bordelon
25,Tug,4.454280e+05,1944,Port Canaveral,Mr. Jonah
26,Cargo,4.616663e+06,2015,Port Canaveral,HOS Briarwood
27,Cargo,2.719740e+06,2009,Port Canaveral,Doug
28,Cargo,2.719740e+06,2009,Port Canaveral,Bob

## Paso 4

## Operaciones de strings:

Realice las siguientes operaciones en el DataFrame df:
-  De la columna home_port extraiga la primera palabra de cada
dato y muestre los resultados.
-  Determine cuántos datos comienzan con la palabra Port y cuántos
datos comienzan con una palabra diferente, ¿Cuáles son las
palabras diferentes?

In [ ]:
# Extraer la primera palabra de cada dato en la columna 'home_port'
df_extrae = df.home_port.str.split(' ').str[0] # Se separa por espacios, se puede utilizar cualquier separador. el str[0] separa el primer elemento separado
df_extrae.value_counts() # Cuenta los valores en la columa home_port

Port    28
Fort     1
Name: home_port, dtype: int64

En la columna home_port, 28 valores comienzan por la palabra Port y 1 comienza por la palabra Fort


- Filtre el DataFrame con los datos que en la columna name
contengan en el string la palabra “GO” y muestre los resultados.

In [ ]:
# Filtrar el DataFrame por los datos que contienen "GO" en la columna 'name'
df_go = df[df['name'].str.contains('GO')] #cuenta las filas con el valor GO
df_go

                type   mass_kg  year_built       home_port         name
6   High Speed Craft  449964.0      2014.0  Port Canaveral  GO Ms Chief
7   High Speed Craft  449964.0      2015.0  Port Canaveral   GO Ms Tree
9              Cargo  502999.0      2007.0  Port Canaveral   GO Pursuit
10             Cargo       NaN      2014.0  Port Canaveral     GO Quest

- Convierta todos los strings de la columna name en palabras con
todas sus letras mayúsculas y muestre los resultados.

In [ ]:
df.name = df.name.str.upper()

- Convierta todos los strings de la columna type en palabras con
todas sus letras minúsculas y muestre los resultados.

In [ ]:
df.type = df.type.str.lower()
df

,type,mass_kg,year_built,home_port,name
0,tug,266712.0,1976.0,Port of Los Angeles,AMERICAN CHAMPION
1,cargo,NaN,NaN,Port of Los Angeles,AMERICAN ISLANDER
2,cargo,NaN,NaN,Port of Los Angeles,AMERICAN SPIRIT
3,barge,NaN,2021.0,Port Canaveral,A SHORTFALL OF GRAVITAS
4,tug,202302.0,1974.0,Port of Los Angeles,BETTY R GAMBARELLA
5,tug,273063.0,1999.0,Port Canaveral,ELSBETH III
6,high speed craft,449964.0,2014.0,Port Canaveral,GO MS CHIEF
7,high speed craft,449964.0,2015.0,Port Canaveral,GO MS TREE
8,cargo,451778.0,2009.0,Port Canaveral,SHANNON
9,cargo,502999.0,2007.0,Port Canaveral,GO PURSUIT
10,cargo,NaN,2014.0,Port Canaveral,GO QUEST
11,cargo,450870.0,2010.0,Port Canaveral,MEGAN
12,tug,508023.0,1995.0,Port Canaveral,HAWK
13,tug,320236.0,1985.0,Fort Lauderdale,HOLLYWOOD
14,barge,NaN,2014.0,Port Canaveral,JUST READ THE INSTRUCTIONS 1
15,barge,NaN,2015.0,Port Canaveral,JUST READ THE INSTRUCTIONS 2
16,tug,NaN,NaN,Port of Los Angeles,KELLY C
17,cargo,440892.0,2002.0,Port of Los Angeles,NRC QUEST
18,barge,NaN,2015.0,Port of Los Angeles,OF COURSE I STILL LOVE YOU
19,tug,89811.0,1976.0,Port of Los Angeles,PACIFIC FREEEDOM
20,tug,351080.0,1974.0,Port of Los Angeles,PACIFIC WARRIOR
21,tug,312072.0,1976.0,Port Canaveral,RACHEL
22,tug,843682.0,1975.0,Port Canaveral,FINN FALGOUT
23,tug,741170.0,2003.0,Port Canaveral,LAUREN FOSS
24,cargo,2097411.0,2014.0,Port Canaveral,SHELIA BORDELON
25,tug,445428.0,1944.0,Port Canaveral,MR. JONAH
26,cargo,4616663.0,2015.0,Port Canaveral,HOS BRIARWOOD
27,cargo,2719740.0,2009.0,Port Canaveral,DOUG
28,cargo,2719740.0,2009.0,Port Canaveral,BOB


- Divida todos los strings de la columna home_port por el espacio
en blanco y muestre los resultados.

In [ ]:
df_div_blanco = df.home_port.str.split()
df_div_blanco

0     [Port, of, Los, Angeles]
1     [Port, of, Los, Angeles]
2     [Port, of, Los, Angeles]
3            [Port, Canaveral]
4     [Port, of, Los, Angeles]
5            [Port, Canaveral]
6            [Port, Canaveral]
7            [Port, Canaveral]
8            [Port, Canaveral]
9            [Port, Canaveral]
10           [Port, Canaveral]
11           [Port, Canaveral]
12           [Port, Canaveral]
13          [Fort, Lauderdale]
14           [Port, Canaveral]
15           [Port, Canaveral]
16    [Port, of, Los, Angeles]
17    [Port, of, Los, Angeles]
18    [Port, of, Los, Angeles]
19    [Port, of, Los, Angeles]
20    [Port, of, Los, Angeles]
21           [Port, Canaveral]
22           [Port, Canaveral]
23           [Port, Canaveral]
24           [Port, Canaveral]
25           [Port, Canaveral]
26           [Port, Canaveral]
27           [Port, Canaveral]
28           [Port, Canaveral]
Name: home_port, dtype: object


- Reemplace todas las palabras ‘Port’ que se encuentran en la
columna home_port por la abreviación ‘P.’ y muestre los
resultados.

In [ ]:
df.home_port= df.home_port.str.replace('Port', 'P.')
df

,type,mass_kg,year_built,home_port,name
0,tug,266712.0,1976.0,P. of Los Angeles,AMERICAN CHAMPION
1,cargo,NaN,NaN,P. of Los Angeles,AMERICAN ISLANDER
2,cargo,NaN,NaN,P. of Los Angeles,AMERICAN SPIRIT
3,barge,NaN,2021.0,P. Canaveral,A SHORTFALL OF GRAVITAS
4,tug,202302.0,1974.0,P. of Los Angeles,BETTY R GAMBARELLA
5,tug,273063.0,1999.0,P. Canaveral,ELSBETH III
6,high speed craft,449964.0,2014.0,P. Canaveral,GO MS CHIEF
7,high speed craft,449964.0,2015.0,P. Canaveral,GO MS TREE
8,cargo,451778.0,2009.0,P. Canaveral,SHANNON
9,cargo,502999.0,2007.0,P. Canaveral,GO PURSUIT
10,cargo,NaN,2014.0,P. Canaveral,GO QUEST
11,cargo,450870.0,2010.0,P. Canaveral,MEGAN
12,tug,508023.0,1995.0,P. Canaveral,HAWK
13,tug,320236.0,1985.0,Fort Lauderdale,HOLLYWOOD
14,barge,NaN,2014.0,P. Canaveral,JUST READ THE INSTRUCTIONS 1
15,barge,NaN,2015.0,P. Canaveral,JUST READ THE INSTRUCTIONS 2
16,tug,NaN,NaN,P. of Los Angeles,KELLY C
17,cargo,440892.0,2002.0,P. of Los Angeles,NRC QUEST
18,barge,NaN,2015.0,P. of Los Angeles,OF COURSE I STILL LOVE YOU
19,tug,89811.0,1976.0,P. of Los Angeles,PACIFIC FREEEDOM
20,tug,351080.0,1974.0,P. of Los Angeles,PACIFIC WARRIOR
21,tug,312072.0,1976.0,P. Canaveral,RACHEL
22,tug,843682.0,1975.0,P. Canaveral,FINN FALGOUT
23,tug,741170.0,2003.0,P. Canaveral,LAUREN FOSS
24,cargo,2097411.0,2014.0,P. Canaveral,SHELIA BORDELON
25,tug,445428.0,1944.0,P. Canaveral,MR. JONAH
26,cargo,4616663.0,2015.0,P. Canaveral,HOS BRIARWOOD
27,cargo,2719740.0,2009.0,P. Canaveral,DOUG
28,cargo,2719740.0,2009.0,P. Canaveral,BOB

1. **De la columna home_port extraiga la primera palabra de cada dato y muestre los resultados:**

Este proceso extrae la primera palabra de cada entrada en la columna home_port, que es útil para separar la ciudad o la sucursal en un conjunto de datos tributario

2. **Determine cuántos datos comienzan con la palabra 'Port' y cuántos datos comienzan con una palabra diferente, ¿Cuáles son las palabras diferentes?**

Este proceso cuenta cuántas entradas comienzan con la palabra 'Port' y cuántas comienzan con una palabra diferente. Luego, identifica las palabras diferentes, lo que puede ayudar a identificar patrones o errores en los datos cuando estan mal descritos.

3. **Filtre el DataFrame con los datos que en la columna name contengan en el string la palabra “GO” y muestre los resultados:**

Este proceso filtra el DataFrame para incluir solo las filas donde la columna name contiene la palabra "GO". Esto es útil para segmentar datos específicos como la ciudad a tributar y los impuestoa aplicados a cierto sector en una empresa especifica.

4. **Convierta todos los strings de la columna name en palabras con todas sus letras mayúsculas y muestre los resultados:**

Este proceso convierte todas las cadenas en la columna name en mayúsculas, lo que puede ayudar a la normalización de datos y facilitar la comparación y búsqueda de información.

5. **Convierta todos los strings de la columna type en palabras con todas sus letras minúsculas y muestre los resultados:**

Similar al paso anterior, esta vez se convierten todas las cadenas en la columna type en minúsculas. Esto también ayuda en la normalización de datos y garantiza coherencia en el formato de texto.

6. **Divida todos los strings de la columna home_port por el espacio en blanco y muestre los resultados:**

Este proceso divide cada cadena en la columna home_port en palabras individuales basadas en el espacio en blanco. Es útil para desglosar información compuesta en partes más manejables, como el cifrado del flex contable de cada stakeholder de la organización.

7. Reemplace todas las palabras ‘Port’ que se encuentran en la columna home_port por la abreviación ‘P.’ y muestre los resultados:**

Este proceso reemplaza todas las instancias de 'Port' en la columna home_port por 'P.', lo que puede ser útil para abreviar ciertos términos y hacerlos más compactos. Tambien permite normalizar criterios de ciertos valores.

**Conclusión sobre las posibilidades de uso en el campo de acción de impuestos tributarios:**

Estas herramientas de manipulación y análisis de datos son valiosas en el campo de impuestos tributarios para diversas tareas, como limpieza y preprocesamiento de datos, segmentación y filtrado basados en criterios específicos, normalización de datos para garantizar coherencia en el formato, y análisis exploratorio de datos para identificar patrones y tendencias.

Por ejemplo, al analizar los datos de declaraciones de impuestos, estas herramientas pueden utilizarse para estandarizar nombres de contribuyentes, filtrar datos relevantes basados en ciertas palabras clave (como tipos de ingresos o deducciones), y dividir direcciones en componentes individuales para análisis geoespacial.

Además, la capacidad de reemplazar términos específicos por abreviaturas puede ser útil para simplificar la presentación de informes y reducir la redundancia en los conjuntos de datos de impuestos.

## Conclusiones

En este trabajo hemos explorado diversas técnicas de manipulación y análisis de datos utilizando Python y la biblioteca pandas. A través de una serie de ejercicios prácticos, hemos abordado tareas comunes como la limpieza de datos, la segmentación, el filtrado y la normalización. Estas técnicas son fundamentales en cualquier proyecto de análisis de datos y ofrecen una sólida base para explorar conjuntos de datos complejos y extraer información significativa.

Concluyo que la limpieza y el preprocesamiento de datos son importantes en etapas inciales en cualquier proyecto de análisis de datos. Garantizar la calidad de los datos es fundamental para obtener resultados precisos y confiables en el análisis. Con frecuencia, la presencia de valores faltantes, datos incorrectos o inconsistentes representa un desafío significativo. Identificar y tratar estos problemas de manera efectiva requiere un conocimiento profundo de los datos y de las técnicas de limpieza disponibles desarolladas en este trabajo.

Adicional, considero que  el poder segmentar y filtrare datos mediante la funciones de pandas según criterios específicos es crucial para explorar conjuntos de datos grandes y complejos. Esto nos permite centrarnos en la información relevante para analizar.
Teniendo presente que definir criterios de segmentación y filtrado puede ser complejo y depender en gran medida del contexto del análisis. el poder conocer la base de datos y sus deversas funciones permite gestionar eficientemente grandes volúmenes de datos puede requerir un uso cuidadoso de los recursos.


Pienso que al tratar con datos no estructurados, con diferencias culturales y lingüísticas que pueden afectar la interpretación de los datos, el poder normalizar datos es esencial para garantizar la coherencia en el formato y facilitar la comparación y el análisis de los datos de cualquier dataset.

En conclusión, el dominio de estas técnicas de manipulación y análisis de datos es esencial para cualquier profesional que trabaje con datos en cualquier campo generando importantes beneficios en términos de eficiencia, precisión y capacidad de análisis.

## Referencias

• Idris, I. (2014). Python Data Analysis. Packt Publishing. (pp. 131-134).

• Samir Madhavan. (2015). Mastering Python for Data Science: Explore the World of Data Science Through Python and Learn How to Make Sense of Data. Packt Publishing. (pp. 11-12).